// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zciggxlohatznkpgjpto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjaWdneGxvaGF0em5rcGdqcHRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2NTE3NTEsImV4cCI6MjA4NzIyNzc1MX0.nljou-PJ3hBv_LD0sciIvPeE0vOUdSEwDYyn4149Jvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});